#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../../vendor/autoload.php';
}

use Yab\QuarxInstaller\Commands\MakeCommand;
use Symfony\Component\Console\Application;

$application = new Application('Quarx', '1.0');

$application->add(new MakeCommand());

$application->run();
